name: Build and publish packages

on:
  push:
    branches:
      - main
      - develop

jobs:
  job1:
    name: Build and publish Xamarin.Forms.EmbeddedAssets
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
        
    - name: Fetch all repository
      run: git fetch --unshallow
      
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    #- name: Change version on csproj file
    #  run: sed -i -e 's/Version>[0-9a-z.-]*</Version>'$GITVERSION_NUGETVERSION'</' ./src/Xamarin.Forms.EmbeddedAssets/Xamarin.Forms.EmbeddedAssets.csproj
      
    - name: Build
      run: dotnet build ./src/Xamarin.Forms.EmbeddedAssets/Xamarin.Forms.EmbeddedAssets.csproj --configuration Release

    - name: Pack
      run: dotnet pack ./src/Xamarin.Forms.EmbeddedAssets/Xamarin.Forms.EmbeddedAssets.csproj --output ./artifacts --configuration Release

    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      #if: github.ref == 'refs/heads/develop'
      with:
        nupkg-path:  './artifacts/*.nupkg'
        repo-owner:  'felipebaltazar'
        gh-user:  'felipebaltazar'
        token:  ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      if: github.ref == 'refs/heads/main'
      with:
        PROJECT_FILE_PATH: ./src/Xamarin.Forms.EmbeddedAssets/Xamarin.Forms.EmbeddedAssets.csproj
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
